import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import "./globals.css";

// Metadata defines the page title and description for the application. You can
// customise these values to fit your brand or project. See Next.js docs for
// additional options.
export const metadata: Metadata = {
  title: "Gunvald Next.js App",
  description: "Generated by create next app with Clerk integration",
};

/**
 * RootLayout wraps your entire application with ClerkProvider and sets up
 * authentication UI in the header. SignedOut users see sign‑in and sign‑up
 * buttons, while signed‑in users see a user profile button. The children
 * prop represents the routed page content.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              {/* Show sign‑in and sign‑up buttons when the user is signed out */}
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              {/* Show user account menu when the user is signed in */}
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}